Update new hdf5 definitions
doriclenses/pyDoric pull request #27
Opened 2023-09-26 18:57 UTC by 4D42

I update all ( I think) the new HDF5 definitions. aka; `ImagesStack -> ImageStack` and `BitsCount -> BitCount`

2023-09-26 18:58 UTC, 4D42 commented
Also I have a question. Do I make it retro compatible? (I assume yeap)

2023-09-27 20:49 UTC, doriclenses requested changes

2023-09-27 20:49 UTC, doriclenses commented on utilities.py
> +    username: Optional[str] = "ImageStack"
Let's change it to not optional

2023-10-05 19:33 UTC, doriclenses approved these changes

2023-10-06 12:06 UTC, kapilseh approved these changes

2023-10-06 12:07 UTC, merged