Add comment and edit the transpose commend
doriclenses/pyDoric pull request #41
Opened 2023-12-14 18:55 UTC by 4D42

Small pull request to add a small comment to try to explain why the reshaping and transposing and also edit the transpose parameter to make a bit more sense

2023-12-14 20:13 UTC, doriclenses commented on CaImAn/caiman_main.py
>      A = A.toarray()
do we need `.toarray()`?

2023-12-14 20:18 UTC, doriclenses commented on CaImAn/caiman_main.py
> +    # Because of the Fortran ordering it need to be reshaped in a specific shape(..., ..., Time) then transposed to (Time, ..., ...) to be saved
`# Before saving, the arrays have to be reshaped with Fortran order and shape (..., ..., Time), then transposed to (Time, ..., ...)`

2023-12-14 20:20 UTC, doriclenses commented on CaImAn/caiman_main.py
> +    # Because of the Fortran ordering it need to be reshaped in a specific shape(..., ..., Time) then transposed to (Time, ..., ...) to be saved
what are (..., ..., Time) and (Time, ..., ...)? (Width, Height, Time) or (Height, Width, Time), ...?

2023-12-14 20:21 UTC, doriclenses requested changes
resolve comments

2023-12-14 21:55 UTC, 4D42 commented on CaImAn/caiman_main.py
>      A = A.toarray()
apparently yeap :(

2023-12-15 15:37 UTC, doriclenses commented on CaImAn/caiman_main.py
>      A = A.toarray()
oki

2023-12-15 15:37 UTC, doriclenses approved these changes

2023-12-15 20:02 UTC, kapilseh approved these changes

2023-12-15 20:14 UTC, merged