Fix bug with spikes name and username
doriclenses/pyDoric pull request #43
Opened 2024-01-03 14:59 UTC by 4D42

The name and username of spikes where not the same as the ROIs. This pull request fix the problem and at the same time create a function to save the spikes (similar to the one for ROIs)

2024-01-03 15:53 UTC, doriclenses requested changes

2024-01-03 15:53 UTC, doriclenses commented on utilities.py
> +def save_spike_signals(
Hmm.. spikes are not necessarily named as ROI 1, ROI 2, etc., so not sure if it's the best way to organize things..
But spikes are always named the same way as the input signals, so I would create the names only once and pass it to the `save_roi_signals()` and `save_signals()` (to save spikes).

2024-01-03 15:53 UTC, doriclenses commented on CaImAn/caiman_main.py
> +            utils.save_spike_signals(S > 0, time_, f, spikes_datapath, attrs_add={"RangeMin": 0, "RangeMax": 0, "Unit": "Intensity"}, spike_ids = ids)
We should save the `S`, not just 0 and 1

2024-01-03 15:53 UTC, doriclenses commented on MiniAn/minian_main.py
> +            utils.save_spike_signals(S.values > 0, time_, f, spikes_datapath, attrs_add={"RangeMin": 0, "RangeMax": 0, "Unit": "AU"}, spike_ids=A.coords["unit_id"].values)
we should save `S.values`

2024-01-03 19:04 UTC, 4D42 commented on MiniAn/minian_main.py
> +        operationCount = utils.operation_count(vpath, f, mn_defs.DoricFile.Group.ROISIGNALS, params_doric, params_source)
I also created a function to generate the operation count. I don't know why I didn't do that before

2024-01-03 19:04 UTC, 4D42 commented on MiniAn/minian_main.py
> +    roi_names         = [defs.DoricFile.Dataset.ROI.format(id_) for id_ in roi_ids]
I did something like that and them I feed to value to the functions that save the ROI and spikes. What do you think?

2024-01-04 16:13 UTC, doriclenses requested changes
I edited a bit, could you check if it's alright?

2024-01-05 17:30 UTC, 4D42 commented
@doriclenses I did some fixes and it should work properly.  I just had some strange bug but now it's working....
@kapilseh can you test to see if minian and caiman work without problem before validating the pullrequest? :)

2024-01-05 19:05 UTC, kapilseh commented
Tested both caiman & minian -> seems to be working fine.

2024-01-05 19:11 UTC, kapilseh commented
@4D42 @doriclenses  maybe I am missing something here-  what do we do with the spike signals saved by minian/caiman. For now, I can not load them ( or they can be loaded ??)

2024-01-05 19:11 UTC, doriclenses approved these changes

2024-01-05 19:29 UTC, doriclenses commented
@kapilseh they can be loaded in the Signal View, so you need to make sure to load ROI signals to the Signal View not Image View, and then load the spikes. I would load only one signal and their spikes, because loading takes time (@4D42 is working on this issue).

2024-01-05 19:33 UTC, kapilseh approved these changes

2024-01-05 20:00 UTC, merged